sudo: required
services:
    - docker

script:
    - docker build -t 31070103/node2 .
    - docker images 31070103/node2

before_deploy:
  - docker login -u $DOCKER_USERNAME  -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: docker push 31070103/node2
  on:
    branch: main
