sudo: required
services:
    - docker

script:
    - docker build -t 31070103/node .
    - docker images 31070103/node

before_deploy:
  - docker login -u DOCKER_USERNAME  -p DOCKER_PASSWORD

deploy:
  provider: script
  script: docker push 31070103/node
  on:
    branch: main