sudo: required
services:
    - docker

script:
    - docker build -t 31070103/node3 .
    - docker images 31070103/node3

before_deploy:
  - docker login -u $DOCKER_USERNAME  -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: 
    - docker tag 31070103/node3 31070103/node3
    - docker push 31070103/node3
  on:
    branch: main
