sudo: required
services:
    - docker

script:
    - docker build -t msleila/node .
    - docker images msleila/node

before_deploy:
  - docker login -u 31070103  -p Ayoub?10

deploy:
  provider: script
  script: docker push 31070103/node
  on:
    branch: master