sudo: required
services:
    - docker

script:
    - docker build -t msleila/node .
    - docker images msleila/node

#before_deploy:
 # - docker login -u <username>  -p <userpassword>

deploy:
  provider: script
  script: docker push 31070103/node
  on:
    branch: master